package GUI;

import BL.Users;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this ftemplate file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author XONI
 */
public class MainForm extends javax.swing.JFrame {
    Users u;
    /**
     * Creates new form NewApplication
     */
    public MainForm() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        new_menu = new javax.swing.JMenu();
        student_menu = new javax.swing.JMenuItem();
        prof_menu = new javax.swing.JMenuItem();
        admin_menu = new javax.swing.JMenuItem();
        drejtimi_menu = new javax.swing.JMenuItem();
        lenda_menu = new javax.swing.JMenuItem();
        Shteti_menu1 = new javax.swing.JMenuItem();
        hyr_ne_test_menu = new javax.swing.JMenuItem();
        rez_std = new javax.swing.JMenuItem();
        krijo_test_menu = new javax.swing.JMenuItem();
        shfaq_rez = new javax.swing.JMenuItem();
        logOut_menu = new javax.swing.JMenuItem();
        exit_menu = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Menu");

        new_menu.setText("New");

        student_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        student_menu.setText("Student");
        student_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_menuActionPerformed(evt);
            }
        });
        new_menu.add(student_menu);

        prof_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        prof_menu.setText("Profesor");
        prof_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prof_menuActionPerformed(evt);
            }
        });
        new_menu.add(prof_menu);

        admin_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        admin_menu.setText("Administrator");
        admin_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_menuActionPerformed(evt);
            }
        });
        new_menu.add(admin_menu);

        drejtimi_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        drejtimi_menu.setText("Drejtim");
        drejtimi_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drejtimi_menuActionPerformed(evt);
            }
        });
        new_menu.add(drejtimi_menu);

        lenda_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        lenda_menu.setText("Lende");
        lenda_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lenda_menuActionPerformed(evt);
            }
        });
        new_menu.add(lenda_menu);

        Shteti_menu1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        Shteti_menu1.setText("Shtet");
        Shteti_menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Shteti_menu1ActionPerformed(evt);
            }
        });
        new_menu.add(Shteti_menu1);

        fileMenu.add(new_menu);

        hyr_ne_test_menu.setMnemonic('s');
        hyr_ne_test_menu.setText("Hyr ne Test");
        hyr_ne_test_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hyr_ne_test_menuActionPerformed(evt);
            }
        });
        fileMenu.add(hyr_ne_test_menu);

        rez_std.setMnemonic('s');
        rez_std.setText("Rezultatet");
        rez_std.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rez_stdActionPerformed(evt);
            }
        });
        fileMenu.add(rez_std);

        krijo_test_menu.setMnemonic('s');
        krijo_test_menu.setText("Krijo Test");
        krijo_test_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krijo_test_menuActionPerformed(evt);
            }
        });
        fileMenu.add(krijo_test_menu);

        shfaq_rez.setMnemonic('s');
        shfaq_rez.setText("Starto/Rezultate Test");
        shfaq_rez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shfaq_rezActionPerformed(evt);
            }
        });
        fileMenu.add(shfaq_rez);

        logOut_menu.setMnemonic('a');
        logOut_menu.setText("Log out");
        logOut_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_menuActionPerformed(evt);
            }
        });
        fileMenu.add(logOut_menu);

        exit_menu.setMnemonic('x');
        exit_menu.setText("Exit");
        exit_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_menuActionPerformed(evt);
            }
        });
        fileMenu.add(exit_menu);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");
        editMenu.setVisible(false);

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setUser(Users u){
       this.u=u; 
    }
    public Users getUser(){
        return u;
    }
    private void exit_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_menuActionPerformed
        //JOptionPane.showConfirmDialog(jMenu1, u)
        
        System.exit(0);
    }//GEN-LAST:event_exit_menuActionPerformed

    private void prof_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prof_menuActionPerformed
        // TODO add your handling code here:
        remove();
        ProfesorRegjisterForm pg = new ProfesorRegjisterForm(this);
        jDesktopPane1.add(pg);
        pg.show();
    }//GEN-LAST:event_prof_menuActionPerformed

    private void student_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_menuActionPerformed
        // TODO add your handling code here:
        System.out.println(jDesktopPane1.getAllFrames().length);
        remove();
        StudentRegjisterForm sg = new StudentRegjisterForm(this);
        jDesktopPane1.add(sg);
        sg.show();
    }//GEN-LAST:event_student_menuActionPerformed

    private void hyr_ne_test_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hyr_ne_test_menuActionPerformed
remove();        
        studentTestFrom stf = new studentTestFrom(u);
        jDesktopPane1.add(stf);
        stf.show();
        
        
    }//GEN-LAST:event_hyr_ne_test_menuActionPerformed
    private void profesorForm(){
//        ProfaForm pf = new ProfaForm(u);
//        jDesktopPane1.add(pf);
//        pf.show();
    }
    private void remove(){
       JInternalFrame [] temp =jDesktopPane1.getAllFrames();
       System.out.println(temp.length);
       for(int i = 0 ;i < temp.length;i++){
           System.out.println(temp[i].toString());
//           jDesktopPane1.remove(i);
           temp[i].dispose();
       }
       jDesktopPane1.updateUI();
    }
    private void admin_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_menuActionPerformed
        remove();
        AdminRegisterForm arf = new AdminRegisterForm(this);
        jDesktopPane1.add(arf);
        arf.show();
    }//GEN-LAST:event_admin_menuActionPerformed

    private void logOut_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_menuActionPerformed
        LoginGUI lg = new LoginGUI();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOut_menuActionPerformed

    private void drejtimi_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drejtimi_menuActionPerformed
        remove();
        ProgramForm pf = new ProgramForm();
        jDesktopPane1.add(pf);
        pf.show();
    }//GEN-LAST:event_drejtimi_menuActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        ProfesorRegjisterForm pg = new ProfesorRegjisterForm(this);
        jDesktopPane1.add(pg);
        pg.show();
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void lenda_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lenda_menuActionPerformed
        remove();
        SubjectsForm s = new SubjectsForm ();
        jDesktopPane1.add(s);
        s.show();
    }//GEN-LAST:event_lenda_menuActionPerformed

    private void krijo_test_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krijo_test_menuActionPerformed
remove();
        TestCreatorForm gt = new TestCreatorForm(u);
        jDesktopPane1.add(gt);
        gt.show();
    }//GEN-LAST:event_krijo_test_menuActionPerformed

    private void Shteti_menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Shteti_menu1ActionPerformed
        remove();
        CountryForm cf = new CountryForm();
        jDesktopPane1.add(cf);
        cf.show();
    }//GEN-LAST:event_Shteti_menu1ActionPerformed

    private void shfaq_rezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shfaq_rezActionPerformed
        remove();
        ShowResults s = new  ShowResults(u);
        jDesktopPane1.add(s);
        s.show();
    }//GEN-LAST:event_shfaq_rezActionPerformed

    private void rez_stdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rez_stdActionPerformed
        remove();
        ResultsStudent r = new ResultsStudent(u);
        jDesktopPane1.add(r);
        r.show();
    }//GEN-LAST:event_rez_stdActionPerformed
    
    
    public JDesktopPane getDesktopPane(){
        return jDesktopPane1;
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new MainForm().setVisible(true);
////            }
////        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Shteti_menu1;
    private javax.swing.JMenuItem admin_menu;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem drejtimi_menu;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exit_menu;
    public javax.swing.JMenu fileMenu;
    public javax.swing.JMenuItem hyr_ne_test_menu;
    private javax.swing.JDesktopPane jDesktopPane1;
    public javax.swing.JMenuItem krijo_test_menu;
    private javax.swing.JMenuItem lenda_menu;
    private javax.swing.JMenuItem logOut_menu;
    private javax.swing.JMenuBar menuBar;
    public javax.swing.JMenu new_menu;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem prof_menu;
    public javax.swing.JMenuItem rez_std;
    public javax.swing.JMenuItem shfaq_rez;
    private javax.swing.JMenuItem student_menu;
    // End of variables declaration//GEN-END:variables

}
