/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Profesors;
import BL.Test;
import BL.Users;
import DAL.ProfesorException;
import DAL.TestiException;
import DAL.UserRepository;
import DAL.TestiRepository;
import Model.TestiTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author arian
 */
public class ShowResults extends javax.swing.JInternalFrame {
    Profesors p;
    Test test;
    
    TestiTableModel ttm = new TestiTableModel();
    TestiRepository tr = new TestiRepository();
    UserRepository ur = new UserRepository();
    /**
     * Creates new form ShowResults
     */
    public ShowResults(Users u) {
        initComponents();
        convert(u);
        tableLoad();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void convert(Users u){
        try{this.p = ur.findByFK(u);
        }
        catch(ProfesorException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void tableLoad(){    
        List<Test> lista = tr.findByProfesor(p);
        ttm.add(lista);
        testTable.setModel(ttm);
        ttm.fireTableDataChanged();
        tabelaSelectedIndexChange();
        
    }
    private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = testTable.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    
                    Test t = ttm.getTesti(selectedIndex);
                    if(t.getTestActive()){
                        activeLabel.setText("TRUE");
                        activeLabel.setForeground(new java.awt.Color(0, 128, 0));
                    }else{
                        activeLabel.setText("FALSE");
                        activeLabel.setForeground(new java.awt.Color(255, 0, 0));
                    }
                    start_btn.setEnabled(true);
                    close_test.setEnabled(true);
                    test = t;
                    show_btn.setEnabled(true);
                }
            }
        });
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        testTable = new javax.swing.JTable();
        start_btn = new javax.swing.JButton();
        show_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        activeLabel = new javax.swing.JLabel();
        cancel_btn = new javax.swing.JButton();
        close_test = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(741, 423));

        testTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(testTable);

        start_btn.setForeground(new java.awt.Color(51, 51, 51));
        start_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play-button.png"))); // NOI18N
        start_btn.setText("Fillo Testin");
        start_btn.setIconTextGap(10);
        start_btn.setEnabled(false);
        start_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_btnActionPerformed(evt);
            }
        });

        show_btn.setForeground(new java.awt.Color(51, 51, 51));
        show_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/task-complete.png"))); // NOI18N
        show_btn.setText("Shfaq Rezultatet");
        show_btn.setIconTextGap(10);
        show_btn.setEnabled(false);
        show_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Testi Aktiv :");

        activeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        activeLabel.setText("         ");

        cancel_btn.setForeground(new java.awt.Color(51, 51, 51));
        cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel-button.png"))); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.setIconTextGap(10);
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        close_test.setForeground(new java.awt.Color(51, 51, 51));
        close_test.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forbidden.png"))); // NOI18N
        close_test.setText("Mbyll Testin");
        close_test.setIconTextGap(10);
        close_test.setEnabled(false);
        close_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_testActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(show_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(close_test, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(activeLabel)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close_test, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_btnActionPerformed
        if(test.getNrQuestions()!=0){
            if(test.getTestActive()){
                JOptionPane.showMessageDialog(this, "Testi tashme eshte aktiv");
            }else{
                test.setTestActive(true);

                try{
                    tr.edit(test);
                }catch(TestiException e){
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
        }else
            JOptionPane.showMessageDialog(this,"Testi nuk ka pytje");
        emptyFields();
        tableLoad();
        
    }//GEN-LAST:event_start_btnActionPerformed

    private void show_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_btnActionPerformed
        if(test.getTestActive()){
            JOptionPane.showMessageDialog(this, "Testi eshte aktiv");
        }else
        {
            ResultsProfesor rp = new ResultsProfesor(test);
            this.getParent().add(rp);
            rp.show();
        }
    }//GEN-LAST:event_show_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
     emptyFields();
       
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void close_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_testActionPerformed
         if(!test.getTestActive()){
            JOptionPane.showMessageDialog(this, "Testi tashme nuk eshte aktiv");
        }else{
            
            test.setTestActive(false);

            try{
                tr.edit(test);
            }catch(TestiException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
         emptyFields();
        tableLoad();
    }//GEN-LAST:event_close_testActionPerformed

private void emptyFields(){
   testTable.clearSelection();
        activeLabel.setText("     ");
        activeLabel.setForeground(new java.awt.Color(255, 255, 255));
        start_btn.setEnabled(false);
         close_test.setEnabled(false);
         show_btn.setEnabled(false);
        
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeLabel;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton close_test;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton show_btn;
    private javax.swing.JButton start_btn;
    private javax.swing.JTable testTable;
    // End of variables declaration//GEN-END:variables
}
