/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Test;
import BL.Users;
import BL.StudentTest;
import DAL.ProfesorException;
import DAL.StudentException;
import DAL.StudentTestRepository;
import DAL.TestiException;
import DAL.TestiRepository;
import Model.TestiTableModel;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import DAL.UserRepository;
import javax.swing.JOptionPane;
/**
 *
 * @author arian
 */
public class studentTestFrom extends javax.swing.JInternalFrame {
    TestiRepository tr = new TestiRepository();
    TestiTableModel ttm  = new TestiTableModel();
    StudentTestRepository str = new StudentTestRepository();
    UserRepository ur = new UserRepository();
    Test t;
    Users u;
    
    public studentTestFrom(Users u) {
        initComponents();
        this.u = u;
        tableLoad();
    }
    private void tableLoad(){
        List<Test> lista = tr.findAll();
        ttm.add(lista);
        testTable.setModel(ttm);
        ttm.fireTableDataChanged();
        tabelaSelectedIndexChange();
         
    }
    private void tabelaSelectedIndexChange(){
        final ListSelectionModel rowSM = testTable.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent Ise){
                if(Ise.getValueIsAdjusting()){
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if(selectedIndex > -1){
                    Test testi = ttm.getTesti(selectedIndex);
                    
                    t=testi;
                    start_test.setEnabled(true);
                  
                    
                }
                
            }
        });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        testTable = new javax.swing.JTable();
        start_test = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(708, 367));

        testTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(testTable);

        start_test.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play-button.png"))); // NOI18N
        start_test.setText("Hyr ne Test");
        start_test.setEnabled(false);
        start_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_testActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start_test, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(start_test, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_testActionPerformed
        boolean temp =true;
        try{
            Test tempT =tr.findById(t.getTestID());
             if(!tempT.getTestActive()){
                temp=false;
                JOptionPane.showMessageDialog(this, "Testi nuk eshte aktiv");
                return;
            }
        }catch( TestiException ex){
            JOptionPane.showMessageDialog(this, "Nuk ka teste");
        }
        try{
            
            StudentTest st =str.findByStudentAndTest(ur.findByFKstd(u),t);
           
            if(st!=null)
                temp=false;
        }catch (ProfesorException | StudentException  e){
            
        }
        if(temp){
            try{
                StudentTest st = new StudentTest();

                st.setStudentID(ur.findByFKstd(u));
                st.setTestID(t);

                str.create(st);
               /* TestOpened to  = new TestOpened(t,st);
                this.getParent().add(to);
                to.show();*/
                CountinueToTest ct = new CountinueToTest(t,st);
                this.getParent().add(ct);
                ct.show();
            }catch(ProfesorException |StudentException  px){

                JOptionPane.showMessageDialog(this, px.getMessage());
            }
        }else
            JOptionPane.showMessageDialog(this, "Ju nuk mund te hyni me ne kete test");
        tableLoad();
    }//GEN-LAST:event_start_testActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton start_test;
    private javax.swing.JTable testTable;
    // End of variables declaration//GEN-END:variables
}
