package GUI;

import BL.Subjects;
import Model.SubjectsTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import DAL.SubjectException;
import DAL.SubjectsRepository;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author XONI
 * 
 */

   
public class SubjectsForm extends javax.swing.JInternalFrame {

    private static ListSelectionModel getSelectionModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    SubjectsRepository por = new SubjectsRepository();
    SubjectsTableModel ptm = new SubjectsTableModel();
    /**
     * Creates new form ProgramForm
     */
    public SubjectsForm() {
        initComponents();
        tabelaLoad();
        this.setLocation(350,40);
        
    }
    
    private void tabelaSelectedIndexChange() {
       final ListSelectionModel rowSM = SubjectsTable.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    Subjects s = ptm.getSubjects(selectedIndex);
                    
                    SubjectField.setText(s.getSubjectName());
                    EctsField.setText(s.getCredits()+"");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        SubjectField = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        SubjectsTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EctsField = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("SUBJECTS");
        setMinimumSize(new java.awt.Dimension(517, 494));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADD SUBJECTS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        SubjectField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        SubjectField.setForeground(new java.awt.Color(51, 51, 51));
        SubjectField.setMargin(new java.awt.Insets(2, 5, 2, 5));
        SubjectField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectFieldActionPerformed(evt);
            }
        });

        SubjectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(SubjectsTable);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Subjects :");

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rubbish-bin.png"))); // NOI18N
        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        Save.setText("SAVE");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel-button.png"))); // NOI18N
        Cancel.setText("CANCEL");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jLabel1.setText("ECTS:");

        EctsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EctsFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(Save, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SubjectField)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(EctsField))))
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SubjectField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(EctsField))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
       try{
            int row = SubjectsTable.getSelectedRow();
            if(row > -1){
                Object [] ob = {"Po","Jo"};
                int i = javax.swing.JOptionPane.showOptionDialog(this, "A dëshironi ta fshini ?", "Fshirja", JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
                if(i==0){
                    Subjects s = this.ptm.getSubjects(row);
                    por.remove(s);
                    
                    tabelaLoad();
                    emptyObject();
                    JOptionPane.showMessageDialog(this, "E dhëna është fshir me sukses !");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Nuk keni selektuar asgjë për të fshir !");
            }
        }catch(SubjectException pe){
            JOptionPane.showMessageDialog(this, pe.getMessage());
        }

                                               

    }//GEN-LAST:event_DeleteActionPerformed
     public void emptyObject(){
        SubjectField.setText("");
        EctsField.setText("");
        
    }
    public void tabelaLoad(){
        List<Subjects> temp = por.findAll();
        ptm.add(temp);
        SubjectsTable.setModel(ptm);
        ptm.fireTableDataChanged();
        tabelaSelectedIndexChange();
   
    }
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        try {
            int row = SubjectsTable.getSelectedRow();
            if (SubjectField.getText().trim().equals("") || !SubjectField.getText().matches("^(?!\\d+$)[a-zA-ZÇçËë\\d\\s]+$"))  {
                JOptionPane.showMessageDialog(this,SubjectField.getText().equals("")?
                        "Mbush emrin e lendes":" Emri i lendes mund te kete vetem shkronja dhe numra", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(SubjectField.getText().length()>50){
            JOptionPane.showMessageDialog(this,"Emri i Lendes  eshte shum i madhe",
                    "Error", JOptionPane.ERROR_MESSAGE);
          }
        
            else if(!EctsField.getText().matches("[0-9]+?")){
                JOptionPane.showMessageDialog(this,EctsField.getText().equals("")?
                        "Mbush ECTS":"ECTS duhet te jet numer i plot pozitiv :", "Error", JOptionPane.ERROR_MESSAGE);
                    
            }
            else if(EctsField.getText().length()>3){
            JOptionPane.showMessageDialog(this,"ECTS  eshte shum i madhe",
                    "Error", JOptionPane.ERROR_MESSAGE);    
          }
        
            else if(Integer.parseInt(EctsField.getText())>15){
                    JOptionPane.showMessageDialog(this,
                        "ECTS Duhet te jet me e vogel se 15", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if( Integer.parseInt((EctsField.getText())) <= 0 ){
                        JOptionPane.showMessageDialog(this,
                                "Nuk mund te kete me pak se 1 ECTS:", "Error", JOptionPane.ERROR_MESSAGE);
                    
            }else {
                if (row == -1) {
                    Subjects s = new Subjects();
                    
                    s.setSubjectName(SubjectField.getText());
                    s.setCredits(Integer.parseInt((EctsField.getText())));
                    
                    por.create(s);
                    JOptionPane.showMessageDialog(this, "E dhëna u ruajt me sukses !");
                    
                } else {
                    Subjects s = this.ptm.getSubjects(row);

                    s.setSubjectName(SubjectField.getText());
                    s.setCredits(Integer.parseInt((EctsField.getText())));
                    por.edit(s);
                    
                    JOptionPane.showMessageDialog(this, "E dhëna u editua me sukses");
                }
                emptyObject();
                tabelaLoad();
            };

        } catch (SubjectException pe) {
            JOptionPane.showMessageDialog(this, pe.getMessage());
    }//GEN-LAST:event_SaveActionPerformed
}
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        emptyObject();
    }//GEN-LAST:event_CancelActionPerformed

    private void SubjectFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectFieldActionPerformed

    private void EctsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EctsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EctsFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField EctsField;
    private javax.swing.JButton Save;
    private javax.swing.JTextField SubjectField;
    private javax.swing.JTable SubjectsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
